config/routes.rb
Rails.application.routes.draw do
  

  resources :bus_routes
  resources :rails_routes
  resources :texi_routes
  devise_for :users
  root 'welcome#mainpage'

  

end

app/models/rails_route.rb
class RailsRoute < ActiveRecord::Base
resourcify
end

app/controllers/rails_routes_controller.rb
class RailsRoutesController < ApplicationController
  before_action :set_rails_route, only: [:show, :edit, :update, :destroy]

  # GET /rails_routes
  # GET /rails_routes.json
  def index
    @rails_routes = RailsRoute.all
  end

  # GET /rails_routes/1
  # GET /rails_routes/1.json
  def show
  end

  # GET /rails_routes/new
  def new
    @rails_route = RailsRoute.new
  end

  # GET /rails_routes/1/edit
  def edit
  end

  # POST /rails_routes
  # POST /rails_routes.json
  def create
    @rails_route = RailsRoute.new(rails_route_params)

    respond_to do |format|
      if @rails_route.save
        format.html { redirect_to @rails_route, notice: 'Rails route was successfully created.' }
        format.json { render :show, status: :created, location: @rails_route }
      else
        format.html { render :new }
        format.json { render json: @rails_route.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rails_routes/1
  # PATCH/PUT /rails_routes/1.json
  def update
    respond_to do |format|
      if @rails_route.update(rails_route_params)
        format.html { redirect_to @rails_route, notice: 'Rails route was successfully updated.' }
        format.json { render :show, status: :ok, location: @rails_route }
      else
        format.html { render :edit }
        format.json { render json: @rails_route.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rails_routes/1
  # DELETE /rails_routes/1.json
  def destroy
    @rails_route.destroy
    respond_to do |format|
      format.html { redirect_to rails_routes_url, notice: 'Rails route was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rails_route
      @rails_route = RailsRoute.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rails_route_params
      params.require(:rails_route).permit(:routename, :origin, :destination, :price)
    end
end

app/helpers/rails_routes_helper.rb
module RailsRoutesHelper
end

app/views/rails_routes/_form.html.erb
<%= form_for(@rails_route) do |f| %>
  <% if @rails_route.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rails_route.errors.count, "error") %> prohibited this rails_route from being saved:</h2>

      <ul>
      <% @rails_route.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :routename %><br>
    <%= f.text_field :routename %>
  </div>
  <div class="field">
    <%= f.label :origin %><br>
    <%= f.text_field :origin %>
  </div>
  <div class="field">
    <%= f.label :destination %><br>
    <%= f.text_field :destination %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rails_routes/edit.html.erb
<h1>Editing Rails Route</h1>

<%= render 'form' %>

<%= link_to 'Show', @rails_route %> |
<%= link_to 'Back', rails_routes_path %>

app/views/rails_routes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Rails Routes</h1>

<table>
  <thead>
    <tr>
      <th>Routename</th>
      <th>Origin</th>
      <th>Destination</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rails_routes.each do |rails_route| %>
      <tr>
        <td><%= rails_route.routename %></td>
        <td><%= rails_route.origin %></td>
        <td><%= rails_route.destination %></td>
        <td><%= rails_route.price %></td>
        <td><%= link_to 'Show', rails_route %></td>
        <td><%= link_to 'Edit', edit_rails_route_path(rails_route) %></td>
        <td><%= link_to 'Destroy', rails_route, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rails route', new_rails_route_path %>

app/views/rails_routes/new.html.erb
<h1>New Rails Route</h1>

<%= render 'form' %>

<%= link_to 'Back', rails_routes_path %>

app/views/rails_routes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Routename:</strong>
  <%= @rails_route.routename %>
</p>

<p>
  <strong>Origin:</strong>
  <%= @rails_route.origin %>
</p>

<p>
  <strong>Destination:</strong>
  <%= @rails_route.destination %>
</p>

<p>
  <strong>Price:</strong>
  <%= @rails_route.price %>
</p>

<%= link_to 'Edit', edit_rails_route_path(@rails_route) %> |
<%= link_to 'Back', rails_routes_path %>