config/routes.rb
Rails.application.routes.draw do
  

  resources :bus_routes
  resources :rails_routes
  resources :texi_routes
  devise_for :users
  root 'welcome#mainpage'

  

end

app/models/texi_route.rb
class TexiRoute < ActiveRecord::Base
resourcify
end

app/controllers/texi_routes_controller.rb
class TexiRoutesController < ApplicationController
  before_action :set_texi_route, only: [:show, :edit, :update, :destroy]

  # GET /texi_routes
  # GET /texi_routes.json
  def index
    @texi_routes = TexiRoute.all
  end

  # GET /texi_routes/1
  # GET /texi_routes/1.json
  def show
  end

  # GET /texi_routes/new
  def new
    @texi_route = TexiRoute.new
  end

  # GET /texi_routes/1/edit
  def edit
  end

  # POST /texi_routes
  # POST /texi_routes.json
  def create
    @texi_route = TexiRoute.new(texi_route_params)

    respond_to do |format|
      if @texi_route.save
        format.html { redirect_to @texi_route, notice: 'Texi route was successfully created.' }
        format.json { render :show, status: :created, location: @texi_route }
      else
        format.html { render :new }
        format.json { render json: @texi_route.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /texi_routes/1
  # PATCH/PUT /texi_routes/1.json
  def update
    respond_to do |format|
      if @texi_route.update(texi_route_params)
        format.html { redirect_to @texi_route, notice: 'Texi route was successfully updated.' }
        format.json { render :show, status: :ok, location: @texi_route }
      else
        format.html { render :edit }
        format.json { render json: @texi_route.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /texi_routes/1
  # DELETE /texi_routes/1.json
  def destroy
    @texi_route.destroy
    respond_to do |format|
      format.html { redirect_to texi_routes_url, notice: 'Texi route was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_texi_route
      @texi_route = TexiRoute.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def texi_route_params
      params.require(:texi_route).permit(:routename, :origin, :destination, :distance, :basicCharge)
    end
end

app/helpers/texi_routes_helper.rb
module TexiRoutesHelper
end

app/views/texi_routes/_form.html.erb
<%= form_for(@texi_route) do |f| %>
  <% if @texi_route.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@texi_route.errors.count, "error") %> prohibited this texi_route from being saved:</h2>

      <ul>
      <% @texi_route.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :routename %><br>
    <%= f.text_field :routename %>
  </div>
  <div class="field">
    <%= f.label :origin %><br>
    <%= f.text_field :origin %>
  </div>
  <div class="field">
    <%= f.label :destination %><br>
    <%= f.text_field :destination %>
  </div>
  <div class="field">
    <%= f.label :distance %><br>
    <%= f.text_field :distance %>
  </div>
  <div class="field">
    <%= f.label :basicCharge %><br>
    <%= f.text_field :basicCharge %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/texi_routes/edit.html.erb
<h1>Editing Texi Route</h1>

<%= render 'form' %>

<%= link_to 'Show', @texi_route %> |
<%= link_to 'Back', texi_routes_path %>

app/views/texi_routes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Texi Routes</h1>

<table>
  <thead>
    <tr>
      <th>Routename</th>
      <th>Origin</th>
      <th>Destination</th>
      <th>Distance</th>
      <th>Basiccharge</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @texi_routes.each do |texi_route| %>
      <tr>
        <td><%= texi_route.routename %></td>
        <td><%= texi_route.origin %></td>
        <td><%= texi_route.destination %></td>
        <td><%= texi_route.distance %></td>
        <td><%= texi_route.basicCharge %></td>
        <td><%= link_to 'Show', texi_route %></td>
        <td><%= link_to 'Edit', edit_texi_route_path(texi_route) %></td>
        <td><%= link_to 'Destroy', texi_route, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Texi route', new_texi_route_path %>

app/views/texi_routes/new.html.erb
<h1>New Texi Route</h1>

<%= render 'form' %>

<%= link_to 'Back', texi_routes_path %>

app/views/texi_routes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Routename:</strong>
  <%= @texi_route.routename %>
</p>

<p>
  <strong>Origin:</strong>
  <%= @texi_route.origin %>
</p>

<p>
  <strong>Destination:</strong>
  <%= @texi_route.destination %>
</p>

<p>
  <strong>Distance:</strong>
  <%= @texi_route.distance %>
</p>

<p>
  <strong>Basiccharge:</strong>
  <%= @texi_route.basicCharge %>
</p>

<%= link_to 'Edit', edit_texi_route_path(@texi_route) %> |
<%= link_to 'Back', texi_routes_path %>