config/routes.rb
Rails.application.routes.draw do
  

  resources :bus_routes
  resources :rails_routes
  resources :texi_routes
  devise_for :users
  root 'welcome#mainpage'

  

end

app/models/bus_route.rb
class BusRoute < ActiveRecord::Base
end

app/controllers/bus_routes_controller.rb
class BusRoutesController < ApplicationController
  before_action :set_bus_route, only: [:show, :edit, :update, :destroy]

  # GET /bus_routes
  # GET /bus_routes.json
  def index
    @bus_routes = BusRoute.all
  end

  # GET /bus_routes/1
  # GET /bus_routes/1.json
  def show
  end

  # GET /bus_routes/new
  def new
    @bus_route = BusRoute.new
  end

  # GET /bus_routes/1/edit
  def edit
  end

  # POST /bus_routes
  # POST /bus_routes.json
  def create
    @bus_route = BusRoute.new(bus_route_params)

    respond_to do |format|
      if @bus_route.save
        format.html { redirect_to @bus_route, notice: 'Bus route was successfully created.' }
        format.json { render :show, status: :created, location: @bus_route }
      else
        format.html { render :new }
        format.json { render json: @bus_route.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bus_routes/1
  # PATCH/PUT /bus_routes/1.json
  def update
    respond_to do |format|
      if @bus_route.update(bus_route_params)
        format.html { redirect_to @bus_route, notice: 'Bus route was successfully updated.' }
        format.json { render :show, status: :ok, location: @bus_route }
      else
        format.html { render :edit }
        format.json { render json: @bus_route.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bus_routes/1
  # DELETE /bus_routes/1.json
  def destroy
    @bus_route.destroy
    respond_to do |format|
      format.html { redirect_to bus_routes_url, notice: 'Bus route was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bus_route
      @bus_route = BusRoute.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bus_route_params
      params.require(:bus_route).permit(:routename, :BusOrigin, :BusDestination, :price)
    end
end

app/helpers/bus_routes_helper.rb
module BusRoutesHelper
end

app/views/bus_routes/_form.html.erb
<%= form_for(@bus_route) do |f| %>
  <% if @bus_route.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bus_route.errors.count, "error") %> prohibited this bus_route from being saved:</h2>

      <ul>
      <% @bus_route.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :routename %><br>
    <%= f.text_field :routename %>
  </div>
  <div class="field">
    <%= f.label :BusOrigin %><br>
    <%= f.text_field :BusOrigin %>
  </div>
  <div class="field">
    <%= f.label :BusDestination %><br>
    <%= f.text_field :BusDestination %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bus_routes/edit.html.erb
<h1>Editing Bus Route</h1>

<%= render 'form' %>

<%= link_to 'Show', @bus_route %> |
<%= link_to 'Back', bus_routes_path %>

app/views/bus_routes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Bus Routes</h1>

<table>
  <thead>
    <tr>
      <th>Routename</th>
      <th>Busorigin</th>
      <th>Busdestination</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bus_routes.each do |bus_route| %>
      <tr>
        <td><%= bus_route.routename %></td>
        <td><%= bus_route.BusOrigin %></td>
        <td><%= bus_route.BusDestination %></td>
        <td><%= bus_route.price %></td>
        <td><%= link_to 'Show', bus_route %></td>
        <td><%= link_to 'Edit', edit_bus_route_path(bus_route) %></td>
        <td><%= link_to 'Destroy', bus_route, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bus route', new_bus_route_path %>

app/views/bus_routes/new.html.erb
<h1>New Bus Route</h1>

<%= render 'form' %>

<%= link_to 'Back', bus_routes_path %>

app/views/bus_routes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Routename:</strong>
  <%= @bus_route.routename %>
</p>

<p>
  <strong>Busorigin:</strong>
  <%= @bus_route.BusOrigin %>
</p>

<p>
  <strong>Busdestination:</strong>
  <%= @bus_route.BusDestination %>
</p>

<p>
  <strong>Price:</strong>
  <%= @bus_route.price %>
</p>

<%= link_to 'Edit', edit_bus_route_path(@bus_route) %> |
<%= link_to 'Back', bus_routes_path %>